version: 0.0
os: linux
files:
  - source: dist
    destination: /var/www/html
hooks:
  ApplicationStop:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/basic_health_check.sh